name: Test Automatizacion Colab
on:
  workflow_dispatch: # Esto nos permite darle al botón de "Play" manualmente

jobs:
  ejecutar-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3 # <- ESTO ES VITAL. Descarga los archivos a la máquina.

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar herramientas
        run: |
          pip install papermill jupyter google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas

      - name: Ejecutar Notebook
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.DRIVE_SERVICE_ACCOUNT }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > secret_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=secret_key.json
          
          echo "Archivos en la carpeta actual antes de ejecutar:"
          ls -la # Esto imprimirá en los logs qué archivos hay realmente
          
          papermill test_automation.ipynb salida.ipynb